### PR TITLE
IpHelper::getCidrBits() enh #6

### PR DESCRIPTION
**Pull request by kamarton**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #6 
| Depend on | #4 

I see less sense in the check method as the getter itself checks.
The invalid IP test does not work properly because it depends on #4.

### CODE REVIEW

**Comment by samdark** [comment]
Seems to fail tests...

**Comment by kamarton** [comment]
> Seems to fail tests...

After https://github.com/yiisoft/network-utilities/pull/8 PR the test will be correct.

**Comment by samdark** [comment]
#8 was merged. Can you push recent master into this pull request branch?

**Comment by kamarton** [comment]
Merged. The tests run correctly.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
