### PR TITLE
IP length constants access fix

### PR DESCRIPTION
**Pull request by kamarton**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

Practical, if available to anyone, is also required for the `Ip` rule. https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/Rule/Ip.php#L306-L311

### CODE REVIEW

**Comment by samdark** [comment]
Does it make sense to move some logic from validator to this package?

**Comment by kamarton** [comment]
> Does it make sense to move some logic from validator to this package?

I'll make issues.

**Comment by kamarton** [comment]
For now, this PR can be omitted. If I think that this package can be used in any code without the yii framework, then it is practical to have these constants available to public.

**Comment by samdark** [comment]
Let's have it.

**Pull request merged**
